### ISSUE TITLE
npm install  didn't work for me 

### ISSUE THREAD

**Issue by sohale** [rajan-g/angular2-google-place-autocomplete#11]
This didn't work for me (on Ubuntu)
`npm install angular2-google-map-auto-complete`

```
...
4489 silly install printInstalled
4490 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
4491 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4492 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4492 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4492 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
4492 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4493 warn tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.
4494 verbose If you need help, you may report this error at:
4494 verbose     <https://github.com/npm/npm/issues>
4495 verbose stack Error: angular2-google-map-auto-complete@2.0.1 postinstall: `typings install`
4495 verbose stack spawn ENOENT
4495 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
4495 verbose stack     at emitTwo (events.js:106:13)
4495 verbose stack     at ChildProcess.emit (events.js:191:7)
4495 verbose stack     at maybeClose (internal/child_process.js:885:16)
4495 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
4496 verbose pkgid angular2-google-map-auto-complete@2.0.1
4497 verbose cwd /home/sohail/cs/angular2/rain-therapy/rain-therapy-app
4498 error Linux 4.4.0-53-generic
4499 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "angular2-google-map-auto-complete"
4500 error node v7.2.1
4501 error npm  v3.10.10
4502 error file sh
4503 error code ELIFECYCLE
4504 error errno ENOENT
4505 error syscall spawn
4506 error angular2-google-map-auto-complete@2.0.1 postinstall: `typings install`
4506 error spawn ENOENT
4507 error Failed at the angular2-google-map-auto-complete@2.0.1 postinstall script 'typings install'.
4507 error Make sure you have the latest version of node.js and npm installed.
4507 error If you do, this is most likely a problem with the angular2-google-map-auto-complete package,
4507 error not with npm itself.
4507 error Tell the author that this fails on your system:
4507 error     typings install
4507 error You can get information on how to open an issue for this project with:
4507 error     npm bugs angular2-google-map-auto-complete
4507 error Or if that isn't available, you can get their info via:
4507 error     npm owner ls angular2-google-map-auto-complete
4507 error There is likely additional logging output above.
4508 verbose exit [ 1, true ]
```

**Comment by ghost** [comment]
Hi there,
I had the same issue this afternoon. I solved it with `npm install tslint@~4.0.0`, with this 

> 4493 warn tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.

I tried `npm install tslint@3.0.0`, and it was solved. Check if it runs for you.

**Comment by atifsaddique211f** [comment]
not working for me as well

**Comment by niravpatel9898** [comment]
same issue for me as well

**Comment by atifsaddique211f** [comment]
I made it work, and its working in this plugin now
https://www.npmjs.com/package/angular2-google-place

**Comment by niravpatel9898** [comment]
I made it work by installing typings:

npm install typings

**Comment by rajan-g** [comment]
you need to install typing.  please try with latest version you won't get issues. I was removed typing from dependency list
